=== hollie/misterhouse/lib/fallback/Net/OSCAR/XML/Protocol.dtd
# The top-level structure is a 'define'.  This defines either a building-block --
# a 'struct' which can get pulled into the various SNACs -- or a SNAC.  SNACs have
# family and subtype, and optionally a channel.
#
# 'ref' is like #include.  There are some basic structures, like userinfo, which appear
# inside multiple SNACs.
#
# Then there are the data types:
#	Numeric types: byte (8-bit), word (16-bit), dword (32-bit).
#	Raw character data: data
#		This can have a 'length prefix' attached to it.
#		The length prefix is a numeric type.  The value of the length prefix
#		is the number of bytes of character data.  The existence of this
#		length prefix is why it might be useful for data to have sub-data.
# Data types can have 'counts'.  A count of -1 represents an infinite count.
# Counted data is passed around as a listref.  For instance, a capabilities block
# is a series of 16-byte values, so by attaching count=-1 to that data item,
# you can pass in a listref with the individual capabilities.  There is also
# fixed-length character data, specified via the length attribute on the data element.
# Data can be null-terminated and padded.  The value for the pad attribute specifies
# the octet value to use for padding.
#
# Things that have, or can have, length prefixes, take an optional 'default_generate'
# attribute.  If set to yes, this will give them a default value of "present but empty".
#
# Note that if you have counted character data, you will get a listref of hashrefs.
# For instance:
#	<data count="-1">
#		<word name="foo" />
#		<word name="bar" />
#	</data>
# Will give you:
#	[
#		{ foo => 1, bar => 2 },
#		{ foo => 1, bar => 4 },
#	]
#
# You can also have tlvchains and TLVs...
#
# If you attach a name to a TLV, as opposed to elements within that TLV,
# presence of that name in the data hash will correspond with presence of
# that TLV in the TLV chain, without regard to the value of said TLV.
#
#
# family=0 is a global fallback SNAC family.  That is:
#	<define family="0" subtype="1" />
# will get picked up on for all SNACs of subtype 1 where there is no define for
# that specific family.

<!ELEMENT oscar (define)+>

<!ELEMENT define (ref|byte|word|dword|data|tlvchain)+>
<!ATTLIST define
	name ID #REQUIRED
	channel CDATA #IMPLIED
	family CDATA #IMPLIED
	subtype CDATA #IMPLIED
	flags1 CDATA #IMPLIED
	flags2 CDATA #IMPLIED
>

<!ELEMENT ref (EMPTY)>
<!ATTLIST ref
	name IDREF #REQUIRED
>

<!ELEMENT byte (#PCDATA)>
<!ATTLIST byte
	name CDATA #IMPLIED
	count CDATA #IMPLIED
>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word
	name CDATA #IMPLIED
	order (network|vax) #DEFAULT network
	count CDATA #IMPLIED
>
<!ELEMENT dword (#PCDATA)>
<!ATTLIST dword
	name CDATA #IMPLIED
	order (network|vax) #DEFAULT network
	count CDATA #IMPLIED
>
<!ELEMENT data (ref|byte|word|dword|data|tlvchain)+>
<!ATTLIST data
	name CDATA #IMPLIED
	prefix_order (network|vax) #DEFAULT network
	length_prefix (byte|word|dword) #IMPLIED
	length CDATA #IMPLIED
	count CDATA #IMPLIED
	default_generate (yes|no) #DEFAULT no
	null_terminated (yes|no) #DEFAULT no
	pad CDATA #IMPLIED
>

<!ELEMENT tlvchain (tlv*)>
<!ATTLIST tlvchain
	subtyped (yes|no) #DEFAULT no <!-- A 'subtyped' TLV is type/subtype/length/value, where subtype and length are both bytes.  It's used in extended status. -->
	count_prefix (byte|word|dword) #IMPLIED
	length_prefix (byte|word|dword) #IMPLIED
	prefix_order (network|vax) #DEFAULT network
	length CDATA #IMPLIED
	default_generate (yes|no) #DEFAULT no
>

<!ELEMENT tlv (ref|byte|word|dword|data|tlvchain)+>
<!ATTLIST tlv
	type CDATA #REQUIRED
	subtype CDATA #IMPLIED <!-- For subtyped TLVs -->

	default_generate (yes|no) #DEFAULT no
	<!--
	     If the TLV has a name, that key being present in the data will
	     correspond to the existance of that TLV, without regard to its value
	-->
	name CDATA #IMPLIED
	<!--
	    If the TLV has a count, it will get listified.
	    Behavior of TLVs which have a count but not a name is undefined.
	-->
	count CDATA #IMPLIED
>

=== hollie/misterhouse/lib/site/Net/OSCAR/XML/Protocol.xml
<?xml version="1.0"?>
<!DOCTYPE oscar SYSTEM "Protocol.dtd">

<oscar>

	<!-- OSCAR primitives -->

	<define name="flap">
		<byte>42</byte> <!-- FLAP packet start indicator -->
		<byte name="channel">2</byte>
		<word name="seqno" />
		<data length_prefix="word" name="msg" />
	</define>

	<define name="snac">
		<word name="family" />
		<word name="subtype" />
		<byte name="flags1" />
		<byte name="flags2" />
		<dword name="reqid" />
		<data name="data" />
	</define>

	<define name="TLV">
		<word name="type" />
		<data length_prefix="word" name="data" />
	</define>
	<define name="subtyped TLV">
		<word name="type" />
		<byte name="subtype" />
		<data length_prefix="byte" name="data" />
	</define>


	<define name="userinfo">
		<data name="screenname" length_prefix="byte" />
		<word name="evil" />
		<tlvchain count_prefix="word">
			<tlv type="1"><word name="flags" /></tlv>
			<tlv type="2"><dword name="membersince" /></tlv>
			<tlv type="3"><dword name="onsince" /></tlv>
			<tlv type="4"><word name="idle" /></tlv>
			<tlv type="13"><data length="16" count="-1" name="capabilities" /></tlv>
			<tlv type="25"><data length="2" count="-1" name="shortcaps" /></tlv>
			<tlv type="29">
				<tlvchain subtyped="yes">
					<tlv type="1" subtype="1"><data name="icon_md5sum" /></tlv>
					<tlv type="2" subtype="-1"><data length_prefix="word" name="extended_status" /></tlv>
				</tlvchain>
			</tlv>
		
			<tlv type="5"> <!-- Only found in channel 3 IMs, why is it in this structure??? -->
				<tlvchain>
					<tlv type="12"><data name="invitation_message" /></tlv>
					<tlv type="10001">
						<word />
						<data length_prefix="byte" name="chat_url" />
					</tlv>
				</tlvchain>
			</tlv> 


			<!-- Self-info only -->
			<tlv type="15"><dword name="session_length" /></tlv>
			<tlv type="10"><dword name="ip" /></tlv>

			<!-- This contains a second copy of this structure - why?! -->
			<tlv type="512" name="sub_info" />
		</tlvchain>
	</define>


	<!-- Random protocol crap -->

	<define name="service request" family="1" subtype="4">
		<word name="type" />

		<!-- Chat extra -->
		<tlvchain>
			<tlv type="1" name="chat">
				<word name="exchange" />
				<data length_prefix="byte" name="url" />
				<word>0</word>
			</tlv>
		</tlvchain>
	</define>
	<define name="error" family="-1" subtype="1">
		<word name="errno" />
		<tlvchain>
			<tlv type="4"><data name="error_details" /></tlv>
		</tlvchain>
	</define>
	<define name="service redirect response" family="1" subtype="5">
		<tlvchain>
			<tlv type="13"><word name="service_type" /></tlv>
			<tlv type="6"><data name="auth_cookie" /></tlv>
			<tlv type="5"><data name="server_ip" /></tlv>
		</tlvchain>
	</define>


	<!-- Signing on -->

	<define name="BOS signon" family="0" subtype="1" channel="1" flags2="6">
		<data name="cookie" />
	</define>

	<define name="signon" family="23" subtype="2">
		<tlvchain>
			<tlv type="1"><data name="screenname" /></tlv>

			<!-- For AIM-style signons -->
			<tlv type="37"><data name="auth_response" /></tlv>
			<!--
			   Set this if the password was hashed before putting
			   it into the auth_response
			-->
			<tlv type="76"><data name="pass_is_hashed" /></tlv>

			<!-- For ICQ-style signons -->
			<tlv type="2"><data name="password" /></tlv>

			<tlv type="3"><data name="clistr" /></tlv>
			<tlv type="22"><word name="supermajor" /></tlv>
			<tlv type="23"><word name="major" /></tlv>
			<tlv type="24"><word name="minor" /></tlv>
			<tlv type="25"><word name="subminor" /></tlv>
			<tlv type="26"><word name="build" /></tlv>
			<tlv type="20"><dword name="subbuild" /></tlv>
			<tlv type="15"><data>en</data></tlv>
			<tlv type="14"><data>us</data></tlv>
			<tlv type="74"><byte>1</byte></tlv>
		</tlvchain>
	</define>
	<define name="ICQ signon request" channel="1">
		<dword>1</dword>
		<ref name="signon" />
	</define>

	<define name="initial signon request" family="23" subtype="6">
		<tlvchain>
			<tlv type="1"><data name="screenname" /></tlv>
			<tlv type="75" default_generate="yes" />
			<tlv type="90" default_generate="yes" />
		</tlvchain>
	</define>

	<!-- How server sends challenge for challenge/response authentication to client -->
	<define name="authentication key" family="23" subtype="7">
		<data name="key" length_prefix="word" />
	</define>

	<!-- Random crap that's part of signon, protocol negotiation -->
	<define name="authorization response" family="23" subtype="3">
		<tlvchain>
			<!-- If there's an error -->
			<tlv type="8"><word name="error" /></tlv>
			<tlv type="4"><data name="error_details" /></tlv>

			<!-- Basic info -->
			<tlv type="1"><data name="screenname" /></tlv>
			<tlv type="17"><data name="email" /></tlv>
			<tlv type="6"><data name="auth_cookie" /></tlv>
			<tlv type="5"><data name="server_ip" /></tlv>

			<!-- Other stuff -->
			<tlv type="19"><word name="registration_status" /></tlv>
			<tlv type="84"><data name="password_change_url" /></tlv>
		</tlvchain>
	</define>
	<define name="rate info response" family="1" subtype="7" />
	<define name="rate acknowledgement" family="1" subtype="8">
		<word>1</word>
		<word>2</word>
		<word>3</word>
		<word>4</word>
		<word>5</word>
	</define>
	<define name="personal info request" family="1" subtype="14" />
	<define name="buddylist rights request" family="19" subtype="2" />
	<define name="buddylist request" family="19" subtype="4" />
	<define name="locate rights request" family="2" subtype="2" />
	<define name="locate rights response" family="2" subtype="3" />
	<define name="buddy rights request" family="3" subtype="2" />
	<define name="buddy rights response" family="3" subtype="3" />
	<define name="IM parameter request" family="4" subtype="4" />
	<define name="IM parameter response" family="4" subtype="5" />
	<define name="BOS rights request" family="9" subtype="2" />
	<define name="BOS rights response" family="9" subtype="3" />
	<define name="self information" family="1" subtype="15"><ref name="userinfo" /></define>
	<define name="minimum report interval" family="11" subtype="2" />
	<define name="MOTD" family="1" subtype="19" />
	<define name="server ready" family="1" subtype="3" />
	<define name="set service versions" family="1" subtype="23">
		<data count="-1" name="service">
			<word name="service_id" />
			<word name="service_version" />
		</data>
	</define>
	<define name="set tool versions" family="1" subtype="2">
		<data count="-1" name="service">
			<word name="service_id" />
			<word name="service_version" />
			<word name="tool_id" />
			<word name="tool_version" />
		</data>
	</define>
	<define name="rate info request" family="1" subtype="6" />
	<define name="rate change" family="1" subtype="10">
		<word />
		<word name="group" />
		<dword name="window" />
		<dword name="clear" />
		<dword name="alert" />
		<dword name="limit" />
		<dword name="disconnect" />
		<dword name="current" />
		<dword name="max" />
	</define>
	<define name="outgoing warning" family="4" subtype="8">
		<word name="is_anonymous" />
		<data name="screenname" length_prefix="byte" />
	</define>
	<define name="incoming warning" family="1" subtype="16">
		<word name="new_level" />
		<ref name="userinfo" />
	</define>
	<define name="memory request" family="1" subtype="31" /> <!-- This was an attempt to block third-party clients by requesting MD5s of portions of the AIM.EXE binary; it is no longer used, huzzah -->
	<define name="host versions" family="1" subtype="24" />
	<define name="session was opened elsewhere" family="9" subtype="2" /> <!-- Before routing (multiple signons of the same screenname) support was added, this error would be sent when the screenname was signed on elsewhere -->
	<define name="add IM parameters" family="4" subtype="2">
		<word name="channel">0</word>
		<dword name="flags">11</dword>
		<word name="max_msg_len">8000</word>
		<word name="max_sender_warn">999</word>
		<word name="max_rcpt_warn">999</word>
		<dword name="min_msg_interval">0</dword>
	</define>
	<define name="buddylist done" family="19" subtype="7" />



	<!-- Buddylist stuff -->

	<define name="buddylist 3 response" family="19" subtype="3" />
	<define name="buddylist" family="19" subtype="6"> <!-- This is supremely weird and fucked up, no bloody way we'll be able to get it in the XML; notably, it is split across multiple SNACs, but not on any sort of coherent boundary, and you have to slice random bits off the front and back...  See OSCAR/Callbacks.pm handler for this protobit. -->
		<data name="data" />		
	</define>
	<define name="buddylist modification acknowledgement" family="19" subtype="14">
		<word name="error" count="-1" />
	</define>
	<define name="buddylist error" family="19" subtype="15">
		<data name="data" />
	</define>

	<!-- Packets are limited to 8k in size, which we could exceed if we try to put too many
		modifications into one packet.  Since we need to flatten one modification at a time
		and stop when we hit the size cap, this stuff is a bit peculiar. -->
	<define name="buddylist modification">
		<data name="entry_name" length_prefix="word" />
		<word name="group_id" />
		<word name="buddy_id" />
		<word name="entry_type" />
		<data name="entry_data" length_prefix="word" />
	</define>
	<define name="buddylist add" family="19" subtype="8"><data name="mods" /></define>
	<define name="buddylist modify" family="19" subtype="9"><data name="mods" /></define>
	<define name="buddylist delete" family="19" subtype="10"><data name="mods" /></define>
	<define name="start buddylist modifications" family="19" subtype="17" />
	<define name="end buddylist modifications" family="19" subtype="18" />
	


	<!-- User information -->

	<define name="get info" family="2" subtype="21">
		<word>0</word>
		<word>1</word>
		<data length_prefix="byte" name="screenname" />
	</define>
	<define name="get away" family="2" subtype="21">
		<word>0</word>
		<word>3</word>
		<data length_prefix="byte" name="screenname" />
	</define>
	<define name="incoming profile" family="2" subtype="6">
		<ref name="userinfo" />
		<tlvchain>
